CREATE TABLE IF NOT EXISTS USERS
(
    USER_ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    LOGIN     VARCHAR,
    USER_NAME VARCHAR,
    EMAIL     VARCHAR,
    BIRTHDAY  DATE
);

CREATE TABLE IF NOT EXISTS USER_FRIENDS
(
    FRIENDSHIP_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID       BIGINT REFERENCES USERS (USER_ID),
    FRIEND_ID     BIGINT REFERENCES USERS (USER_ID)
);

CREATE TABLE IF NOT EXISTS CATEGORIES
(
    CATEGORY_ID   INT PRIMARY KEY,
    CATEGORY_NAME VARCHAR
);

CREATE TABLE IF NOT EXISTS RATINGS
(
    RATING_ID   INT PRIMARY KEY,
    RATING_NAME VARCHAR
);

CREATE TABLE IF NOT EXISTS FILMS
(
    FILM_ID      BIGINT PRIMARY KEY AUTO_INCREMENT,
    FILM_NAME    VARCHAR,
    DESCRIPTION  VARCHAR,
    RELEASE_DATE DATE,
    DURATION     INT,
    RATING       INT REFERENCES RATINGS (RATING_ID)
);

CREATE TABLE IF NOT EXISTS FILM_CATEGORIES
(
    FILM_CATEGORY_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    FILM_ID          BIGINT REFERENCES FILMS (FILM_ID),
    CATEGORY_ID      INT REFERENCES CATEGORIES (CATEGORY_ID)
);

CREATE TABLE IF NOT EXISTS FILM_USER_LIKES
(
    LIKE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    FILM_ID BIGINT REFERENCES FILMS (FILM_ID),
    USER_ID BIGINT REFERENCES USERS (USER_ID)
);

MERGE INTO RATINGS
    VALUES (1, 'G'),
           (2, 'PG'),
           (3, 'PG-13'),
           (4, 'R'),
           (5, 'NC-17');

MERGE INTO CATEGORIES
    VALUES (1, 'Комедия'),
           (2, 'Драма'),
           (3, 'Мультфильм'),
           (4, 'Триллер'),
           (5, 'Документальный'),
           (6, 'Боевик');